### ISSUE TITLE
[bug] Cover Doesn't Display

### ISSUE THREAD

**Issue by Tetrajak** [gigaherz/Guidebook#30]
Minecraft Version: 1.12.2
Forge Build: 2572
Mod Version: 1.7.3

So, following the demo to the letter, I get a missing texture where there should be a cover image. The book otherwise works in-game.

Full book: https://pastebin.com/ZpxtKYvH
Book cover and content in-game: https://imgur.com/35da1Sa
Book cover image and location: https://imgur.com/w5zV15J

**Comment by gigaherz** [comment]
I noticed that bug a while ago, but I didn't have time to work on this mod back then. Thanks for reminding me. I'll take a look as soon as I can.

**Comment by gigaherz** [comment]
Hello!
I have released a brand-new (beta) version of Guidebook, which MAY break existing a few books, but among other things, it should fix the cover issue.
You can find the beta release here: https://minecraft.curseforge.com/projects/guidebook/files/2518170

**Comment by kreezxil** [comment]
I've got this beta release 1.12.2-2.0.0 and the cover is still not working.

**Comment by gigaherz** [comment]
Strange... will take a look...
