### ISSUE TITLE
Bug with text position after resize client window

### ISSUE THREAD

**Issue by KorDum** [gigaherz/Guidebook#59]
Guidebook 2.6.0

If I open the book with default window size, all OK:
![image](https://user-images.githubusercontent.com/1331559/41783336-50adb72c-7645-11e8-9739-56513f26bfc5.png)

If I resize the window:
![image](https://user-images.githubusercontent.com/1331559/41783382-66a0cba0-7645-11e8-9200-23c374581135.png)

**Comment by gigaherz** [comment]
Strange, I thought I fixed that ...
Closing and reopening the book should fix it, though? If it does not, then I have to look into it.

**Comment by KorDum** [comment]
Floating bug. I can't reproduce anymore. I'm trying to break it yet.

**Comment by KorDum** [comment]
No, if I reopen the book, problem remains.
Steps for reproduce:
1. add demobook from examples
2. open book
3. close book
4. reopen book
5. resize window

**Comment by gigaherz** [comment]
I'll take a look, thanks for the report!

**Comment by gigaherz** [comment]
v2.6.5 has been uploaded to maven, and will be available in curseforge after it's reviewed. It should fix this.

**Comment by KorDum** [comment]
The bug is still reproduce in 2.6.5. Same steps from above.
![image](https://user-images.githubusercontent.com/1331559/41806919-e0fb08fa-76ce-11e8-8e33-4c0578a60692.png)
